plugins = []
headers = []
redirects = []

[functions]

 [functions."*"]

[build]
base = "/Users/thor3/pqc-work/signature-web"
[build.environment]
  NODE_VERSION = "20"
command = "npm run build"
publish = "dist"
[build.environment]
[build.processing]
[build.processing.css]
[build.processing.html]
[build.processing.images]
[build.processing.js]
[build.services]
