[build]
  base = "/Users/thor3/pqc-work/signature-web"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]

  [functions."*"]

[[headers]]

[[redirects]]
